services:
  web:
    build: .
    env_file: ".env"
    ports:
      - "4000:4000"
    depends_on:
      - "postgres"
  postgres:
    image: "postgres:14.2-bullseye"
    env_file: ".env"
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres: {}
